### ISSUE TITLE
Recent changes bad filter

### ISSUE THREAD

**Issue by Kycko** [kynikos/wiki-monkey#227] opened 2017-07-10 13:51 UTC
Seems like not all russian articles are listed under corresponding header:

![2017-07-10 16-50-31](https://user-images.githubusercontent.com/12460263/28021246-ecb8d4c0-658f-11e7-9041-24dee2f88fc3.png)

**Comment by kynikos** [comment] 2017-07-10 14:04
Hi, the problem is with redirect pages, which indeed aren't filtered properly (it happens with all languages), it's possible that a MediaWiki update changed how redirects are displayed in the RecentChanges, and Wiki Monkey stopped correctly parsing them, or perhaps I just never noticed because often non-English redirects don't have a language tag and they appear among the English articles by default.
I'll have a look at it in the weekend, thanks for the report!

**Comment by kynikos** [comment] 2017-07-18 12:53
This should be fixed in 3.0.3, already released.

**Closed by kynikos** 2017-07-18 12:53 UTC
Labels: defect, plugin/mod

**Comment by Kycko** [comment] 2017-07-18 17:44
Yup, I confirm ^_^
